# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x05stamp\"\x17\n\x03Req\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x16\n\x03Res\x12\x0f\n\x07message\x18\x01 \x01(\t2.\n\x05Stamp\x12%\n\x0b\x43reateStamp\x12\n.stamp.Req\x1a\n.stamp.Resb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQ']._serialized_start=21
  _globals['_REQ']._serialized_end=44
  _globals['_RES']._serialized_start=46
  _globals['_RES']._serialized_end=68
  _globals['_STAMP']._serialized_start=70
  _globals['_STAMP']._serialized_end=116
# @@protoc_insertion_point(module_scope)
