// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: file.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "stamp";

export interface Req {
  filename: string;
}

export interface Res {
  message: string;
}

function createBaseReq(): Req {
  return { filename: "" };
}

export const Req = {
  encode(message: Req, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.filename !== "") {
      writer.uint32(10).string(message.filename);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Req {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.filename = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Req {
    return { filename: isSet(object.filename) ? globalThis.String(object.filename) : "" };
  },

  toJSON(message: Req): unknown {
    const obj: any = {};
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Req>, I>>(base?: I): Req {
    return Req.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Req>, I>>(object: I): Req {
    const message = createBaseReq();
    message.filename = object.filename ?? "";
    return message;
  },
};

function createBaseRes(): Res {
  return { message: "" };
}

export const Res = {
  encode(message: Res, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Res {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Res {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: Res): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Res>, I>>(base?: I): Res {
    return Res.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Res>, I>>(object: I): Res {
    const message = createBaseRes();
    message.message = object.message ?? "";
    return message;
  },
};

export interface Stamp {
  CreateStamp(request: Req): Promise<Res>;
}

export const StampServiceName = "stamp.Stamp";
export class StampClientImpl implements Stamp {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || StampServiceName;
    this.rpc = rpc;
    this.CreateStamp = this.CreateStamp.bind(this);
  }
  CreateStamp(request: Req): Promise<Res> {
    const data = Req.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateStamp", data);
    return promise.then((data) => Res.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
